"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { History, Zap } from "lucide-react";

import type { ShiftKind } from "@universe/contracts";

import { api, errorMessage } from "@/lib/api";
import { useI18n } from "@/lib/i18n";
import {
  actualListKey,
  actualListQueryOptions,
} from "@/lib/queries/fleet-actual";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogActions,
  DialogBody,
  DialogIcon,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  DNote,
  FootSum,
  Panel,
  PanelFoot,
  Toolbar,
  ToolbarGroup,
  ToolbarTitle,
} from "@/components/ui/panel";
import { Select } from "@/components/ui/select";
import { StateBox } from "@/components/ui/state-box";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useToast } from "@/components/ui/toast";

import { siteClock } from "./data";

/** Today, site-local, for the generate dialog's default. */
function todayISO() {
  const d = new Date();
  const p = (n: number) => `${n < 10 ? "0" : ""}${n}`;
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`;
}

/**
 * Tab ACTUAL — the boards the engine has generated, newest first.
 *
 * The static port kept a local array here and mutated it, with "Tambah" as a
 * lock marker and "Generate" as a fixed set of numbers. Both are gone: the
 * board is generated by `spare-validate` twice a day, and the button here only
 * asks for it early or again. There is no lock — the board is never frozen, so
 * a row that has been generated is still a row a supervisor can correct.
 */
export function ActualTable({ canManage }: { canManage: boolean }) {
  const { t } = useI18n();
  const { pushToast } = useToast();
  const router = useRouter();
  const queryClient = useQueryClient();

  const listQ = useQuery(actualListQueryOptions());
  const rowsAll = React.useMemo(() => listQ.data ?? [], [listQ.data]);

  const [shiftF, setShiftF] = React.useState("");
  const [d1, setD1] = React.useState("");
  const [d2, setD2] = React.useState("");
  const [genOpen, setGenOpen] = React.useState(false);
  const [genDate, setGenDate] = React.useState(todayISO());
  const [genShift, setGenShift] = React.useState<ShiftKind>("day");

  const shiftLabel = (s: ShiftKind) =>
    s === "day" ? t.faShiftPagi : t.faShiftMalam;

  const generate = useMutation({
    mutationFn: async (input: { date: string; shift: ShiftKind }) => {
      const result = await api.v1["fleet-allocation"]
        .actual({ date: input.date })({ shift: input.shift })
        .generate.post();
      if (result.error) throw result.error;
      return result.data;
    },
    onSuccess: async (data, input) => {
      await queryClient.invalidateQueries({ queryKey: actualListKey });
      setGenOpen(false);
      pushToast(
        "success",
        t.faGenToastT,
        `${input.date} — ${shiftLabel(input.shift)} · ${data?.units ?? 0} unit`
      );
    },
    onError: (error) =>
      pushToast("error", t.faGenTitle, errorMessage(error, t.loginErr)),
  });

  const rows = rowsAll.filter((r) => {
    if (shiftF && r.shift !== shiftF) return false;
    if (d1 && r.date < d1) return false;
    if (d2 && r.date > d2) return false;
    return true;
  });

  return (
    <>
      <Panel>
        <Toolbar>
          <ToolbarTitle>{t.fahTitle}</ToolbarTitle>
          <ToolbarGroup>
            <Select
              wrapperClassName="w-[150px]"
              value={shiftF}
              onChange={(e) => setShiftF(e.target.value)}
              aria-label={t.allShift}
            >
              <option value="">{t.allShift}</option>
              <option value="day">{t.faShiftPagi}</option>
              <option value="night">{t.faShiftMalam}</option>
            </Select>
            <div className="flex items-center gap-2">
              <Input
                type="date"
                className="w-40 font-mono"
                value={d1}
                onChange={(e) => setD1(e.target.value)}
                aria-label={t.lblDate}
              />
              <span className="text-(--text-tertiary)">—</span>
              <Input
                type="date"
                className="w-40 font-mono"
                value={d2}
                onChange={(e) => setD2(e.target.value)}
                aria-label={t.lblDateTo}
              />
            </div>
            {canManage ? (
              <Button
                onClick={() => {
                  setGenDate(todayISO());
                  setGenShift("day");
                  setGenOpen(true);
                }}
              >
                <Zap />
                {t.faGenBtn}
              </Button>
            ) : null}
          </ToolbarGroup>
        </Toolbar>

        {rows.length ? (
          <div className="overflow-x-auto">
            <Table className="min-w-[1000px]">
              <TableHeader>
                <tr>
                  <TableHead>{t.lblDate}</TableHead>
                  <TableHead>{t.thShift}</TableHead>
                  <TableHead>{t.fahThGen}</TableHead>
                  <TableHead>{t.fahThAlloc}</TableHead>
                  <TableHead>{t.fahThPlan}</TableHead>
                  <TableHead>{t.faViaSpare}</TableHead>
                  <TableHead>{t.faViaManual}</TableHead>
                  <TableHead>{t.faDowntime}</TableHead>
                  <TableHead />
                </tr>
              </TableHeader>
              <TableBody>
                {rows.map((r) => (
                  <TableRow key={`${r.date}-${r.shift}`}>
                    <TableCell className="font-mono whitespace-nowrap">
                      {r.date}
                    </TableCell>
                    <TableCell>{shiftLabel(r.shift)}</TableCell>
                    <TableCell className="font-mono whitespace-nowrap">
                      {siteClock(r.generatedAt)}
                    </TableCell>
                    <TableCell className="font-mono">{r.total}</TableCell>
                    <TableCell className="font-mono">{r.viaPlan}</TableCell>
                    <TableCell>
                      {r.viaSpare ? (
                        <Badge variant="warning" dot>
                          {r.viaSpare}
                        </Badge>
                      ) : (
                        <span className="font-mono text-(--text-tertiary)">
                          0
                        </span>
                      )}
                    </TableCell>
                    <TableCell>
                      {r.viaManual ? (
                        <Badge variant="info" dot>
                          {r.viaManual}
                        </Badge>
                      ) : (
                        <span className="font-mono text-(--text-tertiary)">
                          0
                        </span>
                      )}
                    </TableCell>
                    <TableCell>
                      {/* The number this screen is for: units nobody is on. */}
                      {r.idle ? (
                        <Badge variant="danger" dot>
                          {r.idle}
                        </Badge>
                      ) : (
                        <Badge variant="success" dot>
                          0
                        </Badge>
                      )}
                    </TableCell>
                    <TableCell className="text-right whitespace-nowrap">
                      <Button
                        variant="secondary"
                        className="h-8 text-[13px]"
                        onClick={() =>
                          router.push(
                            `/fleet-allocation/detail?date=${r.date}&shift=${r.shift}`
                          )
                        }
                      >
                        {t.fahDetail}
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : (
          <StateBox
            icon={<History className="text-(--color-primary-bright)" />}
            title={t.fahEmptyT}
            body={t.fahEmptyB}
          />
        )}

        <PanelFoot>
          <FootSum>
            <b>{rows.length}</b> {t.fahSumB}
          </FootSum>
        </PanelFoot>
      </Panel>

      <DNote title={t.fahNoteT}>{t.fahNoteB}</DNote>

      <Dialog
        open={genOpen}
        onClose={() => setGenOpen(false)}
        className="w-[min(480px,100%)]"
        labelledBy="fagen-t"
      >
        <DialogIcon variant="info">
          <Zap />
        </DialogIcon>
        <DialogTitle id="fagen-t">{t.faGenTitle}</DialogTitle>
        <DialogBody>{t.faGenDlgB}</DialogBody>
        <div className="mt-4 flex flex-col gap-3">
          <label className="flex flex-col gap-1.5 text-xs font-semibold text-(--text-secondary)">
            {t.lblDate}
            <Input
              type="date"
              className="w-full font-mono"
              value={genDate}
              onChange={(e) => setGenDate(e.target.value)}
            />
          </label>
          <label className="flex flex-col gap-1.5 text-xs font-semibold text-(--text-secondary)">
            {t.thShift}
            <Select
              value={genShift}
              onChange={(e) => setGenShift(e.target.value as ShiftKind)}
            >
              <option value="day">{t.faShiftPagi}</option>
              <option value="night">{t.faShiftMalam}</option>
            </Select>
          </label>
        </div>
        <DialogActions>
          <Button variant="ghost" onClick={() => setGenOpen(false)}>
            {t.btnCancel}
          </Button>
          <Button
            disabled={generate.isPending}
            onClick={() => generate.mutate({ date: genDate, shift: genShift })}
          >
            <Zap />
            {t.faGenBtn}
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}
